-- AlterTable
ALTER TABLE `User` ADD COLUMN `facility` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `title` VARCHAR(191) NULL;
